---
name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo sh -c "
            apt install python3-pip

            # The python3-poetry in the Ubuntu repos is too old so we install
            # using pip.
            pip install poetry
          "
          poetry install
      - name: Analyse the code with pylint
        run: |
          poetry run bash -c "
            pylint **/*.py

            echo 'Masking pylint messages that are neither an error (2^0) nor'
            echo 'a warning (2^1) from its exit code so that they do not abort'
            echo 'the CI build.'

            exit $(( $? & 3 ))
          "
      - name: Run unit tests
        run: |
          poetry run test
